export const DEFAULT_PAGE = 0;
export const DEFAULT_LATEST_TIMESTAMP_STRING = Math.trunc(Date.now() / 1000).toString()
export const DEFAULT_LATEST_TIMESTAMP = Math.trunc(Date.now() / 1000)
export const DEFAULT_PAGE_SIZE = 10;
export const DEFAULT_START_TIMESTAMP = 100;
export const DEFAULT_ADDRESS = '0x'
export const DEFAULT_MAX_TRANSACTION_RETURN = 10;
export const DEFAULT_MAX_RESULT_COUNT = 10;
export const DEFAULT_TOKEN_ADDRESS = '0x'
export const DEFAULT_INVALID_VALUE = null
export const DEFAULT_INVALID_PERCENTAGE = null
export const DEFAULT_CONTRACT_VERIFICATION = false;
export const DEFAULT_LOGO_PATH = undefined;
export const DEFAULT_LIMIT = 10;
export const DEFAULT_CHAIN_ID = '0x1';
export const DEFAULT_MAX_TRANSACTION_REQUEST = 20;
export const DEFAULT_SCORE = 0;
export const DEFAULT_NATIVE_BALANCE = 0;
export const DEFAULT_LABEL = 'Unknown';